name: PR version bumped
on:
  pull_request:
    types: [ assigned, edited, opened, ready_for_review, reopened, synchronize ]
    branches: [ main, master ]
  workflow_dispatch:  # Go to [Actions] - select PR version bumped -> [Run workflow]
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
    - name: clone PR branch
      uses: actions/checkout@master
      with:
        fetch-depth: 1
        path: pull_request
        ref: ${{ '{{' }} github.event.pull_request.head.ref {{ '}}' }}
    - name: clone base branch
      uses: actions/checkout@master
      with:
        fetch-depth: 1
        path: base
        ref: ${{ '{{' }} github.event.pull_request.base.sha {{ '}}' }}
    - name: version-compare
      id: version-compare
      run: |
        PR_VER=$(grep "current_version = " pull_request/setup.cfg|cut -d " " -f3)
        CUR_VER=$(grep "current_version = " base/setup.cfg|cut -d " " -f3)
        if [[ $PR_VER > $CUR_VER ]]; then
            echo "All good!"; else
            echo "new version is not greater than current version!"
            echo "Go to [Actions] -> select "New Version" -> [Run workflow] ->"
            echo "Select PR branch -> enter appropriate type -> [Run workflow]"
            exit 1
        fi
